title: "Zennで本を執筆する！本の作成マニュアル"
summary: |-
  この本は「Zennで本を作成する方法」を解説したものです。
  あなたが詳しい技術やサービスについての知見や、ユニークな経験があるのであれば、体系化して本にまとめましょう。 細切れの情報は無料で手に入ることも多いですが、体系化された情報は貴重です。 堂々と値段をつけて販売してみましょう。
topics: []
published: false
price: 0 # 有料の場合200〜5000
