name: Test zenn-cli

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test --updateSnapshot
        working-directory: packages/zenn-cli
