name: Lint zenn-editor

on:
  pull_request:
    branches:
      - main
      - canary
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # pnpm installも実行されます
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Lint
        run: pnpm strict:lint
