name: Lint zenn-editor

on:
  pull_request:
    branches:
      - main
      - canary
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: | # pnpm installも実行されます
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Lint
        run: pnpm strict:lint
