name: Test zenn-editor

on:
  pull_request:
    branches:
      - main
      - canary
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: | # pnpm installも実行されます
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm build

      - name: Run tests for zenn-markdown-html
        run: pnpm test
        working-directory: packages/zenn-markdown-html

      - name: Run tests for zenn-cli
        run: pnpm test
        working-directory: packages/zenn-cli
